### ISSUE TITLE
Can't export Rmd to Rcloud using RStudio Addin

### ISSUE THREAD

**Issue by useless5771** [att/rcloud.rmd#23]
RStudio version: 1.0.136
R version 3.2.3 
rcloud.rmd version: first seen: a0c1ea29fdcc151f0e1a1be7b5bc286dedf1e506 reproduced with: 5fbad2366222e4d34dd691de17d72608289e8425 

I created a file named: test-multi-col.Rmd with contents of: http://rmarkdown.rstudio.com/flexdashboard/index.html#multiple-columns

With the Rmd file opened in RStudio when I click the 'Tools->Addins->Export to RCloud notebook' just the following error message is displayed:

> No Rmd file is open for RCloud export.

Tried with Rmd file being in the root of RStudio project (hence R working directory) and in some other location. In both cases the export fails.

**Comment by gordonwoodhull** [comment]
I think this has to be a bug in `rcloud.rmd`. I'm using the same version of RStudio (and R 3.2.2 but that shouldn't matter.) The above error is coming from `R/rstudio.R`

I notice that if I close all files, I get a non-helpful error when I think I should get the above error, so this is also buggy.

Dialog says:
> R code execution error

And console says:
> Error in blks | head(c(TRUE, txts), -1) : 
>  operations are possible only for numeric, logical or complex types

**Comment by useless5771** [comment]
Ok, thanks, I will have a look at this.

**Comment by useless5771** [comment]
Installing rstudioapi from guthub solved my issue, I have this version installed now:
rstudioapi       0.6     2017-05-03 Github (rstudio/rstudioapi@bc145dd)

It appears that rstudioapi package on CRAN has a bug in rstudioapi::getSourceEditorContext() which fails to return currently viewed file in the editor when executed from RStudio console and/or addin.

When I tried to reproduce your issue I got expected message:

> No Rmd file is open for RCloud export.

**Comment by useless5771** [comment]
Raised ticket rstudio/rstudioapi#40
